source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'sinatra-asset-pipeline'
gem 'foundation'
gem 'sass', '~> 3.4.0'
gem 'compass', '~> 1.0'
gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-foundation'
gem 'sinatra-zero_clipboard'